name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'none, major, minor or patch'
        required: true
      versionSuffix:
        description: 'suffix to add to the version to be released'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: tbureck/actions-dotnet-release@main
        with: 
          project-file: 'src/TBureck.BuildingBlocks.Domain/TBureck.BuildingBlocks.Domain.csproj'
          release-type: ${{ github.event.inputs.releaseType }}
          version-suffix: ${{ github.event.inputs.versionSuffix }}
          dry-run: true
          
